### ISSUE TITLE
Free@home Busch Jäger

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#28]
https://forum.iobroker.net/viewtopic.php?t=5479

Migrated from Trello with 4 votes

**Comment by Apollon77** [comment]
Homebridge modules exist: https://www.npmjs.com/package/homebridge-buschjaeger as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by TheSpirit** [comment]
tried this. but I am unable to git clone sstadlberger api

![bildschirmfoto 2018-06-18 um 19 32 11](https://user-images.githubusercontent.com/6056918/41552356-cea9e7e6-732e-11e8-839e-eec800791ab5.png)

**Comment by Apollon77** [comment]
?! What you want to clone and why?

**Comment by Apollon77** [comment]
Ahh I see ... there is kind of a Library. but this has nothing to do with ioBroker and also not with Homebridge.

**Comment by NeoBlack** [comment]
any news regarding this adapter? Is there any test version or something I could try out?

**Comment by mabasger** [comment]
The API from Busch Jäger is quite well documented (https://developer.eu.mybuildings.abb.com/tutorials). But I am lacking the time to create a adapter.
There is a javascript module https://github.com/henry-spanka/freeathome-api - I will try to do some fast dirty hacks with some scripts and this module

**Comment by avealer** [comment]
Hello i´m an absolut Beginner.
Is there any Chance to get an Adapter working on IO Broker for Free@Home.
Thanks for your Answers.
Alex

**Comment by Apollon77** [comment]
If a developer finds time for this adapter and have the hardware then there might be an adapter somewhen. Show your interest in getting the adapter by using thumbs up on first post that developers can see how many users are Interested.

**Comment by mobilutz** [comment]
FYI: I just started with the development of a f@h adapter.
I am not sure how fast I will get it finished, but I just wanted to write it down here. And if someone wants to help me, I am more than willing to have support 😉 

I am using https://github.com/henry-spanka/freeathome-api for the connection and https://github.com/henry-spanka/homebridge-buschjaeger as a guide on what should be implemented in the end.

As I only have blinds for f@h in my house, any help (when I am at that point) with other accessories would be good.

**Comment by avealer** [comment]
Hello Mobilutz,
Thank you for starting with development of this adapter. 
I'm just a User not a developer.... but I'm waiting so long for an Adapter of free@home in Iobroker. 
I want to support you... perhaps I can help you with testing the adapter. 
I have 
>Heating Actors 
> Blinds
> Light Actors
Let me know if you need help. 
We can communicate in German if you want to I'm from Bavaria. 
Greetings from Avealer

**Comment by matelso** [comment]
Hello Mobilutz,

I am just a user too. But I have a little experience in reading "code".
If I can help you in any way, let me know.
I am running a f@h system with lights, blinds, welcome etc.
I connected f@h to my alexa. I also use Phillips Hue Bridge, Broadlink RMpro, flic buttons, AVM Fritz Smart Home devices etc. So I would be happy to use all these things in iobroker.

I am german too, Kaiserslautern area - so we could also talk german if this helps.

Thank you so much for working on this iobroker adapter with the f@h API. I just found out about this new API a few weeks ago. Now I am hoping to get this working soon. - so excited.

**Comment by mobilutz** [comment]
@avealer @matelso 

I have a first pre beta version of the adapter which is working now for two days locally.

Right now, there is no specific logic for any type of accessory, it just reads all the information from the system access point and creates state for all of them.
And it also allows setting any state inside the system access point.

Please test it out locally, and comment on whatever is missing/failing etc.
https://github.com/mobilutz/iobroker.freeathome

Please do not write here, but in the repository of that adapter.

Locally, I use YAHKA to directly manipulate the window blind information from the system access point directy But that functionality should of course be inside the adapter. But that takes time ;)

PS: If you want german support, just message me.

**Comment by avealer** [comment]
Hello Mobilutz, 
how can i get in contact with you?

**Comment by mobilutz** [comment]
@avealer There is a contact address on the GibHub page.

**Comment by lilskill** [comment]
Really nice. I start my project this week. I have also free@home installed in my house, and want to get it work with iobroker. Thanks for your work, i will post after a few tests.

**Comment by lilskill** [comment]
can anyone help? always getting this when trying to start the api:

Error: Cannot find module '/home/pi/freeathome-api/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/freeathome-api/bin/freeathome-api:13:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)


Used This:
Globally
Run npm install freeathome-api -g
See Configuration section.
Start the API with freeathome-api
Star the repository ;)

and used the config-example.json

**Comment by Apollon77** [comment]
I have no idea about your code, but you install the library globally but try to require the library file "locally" in home/pi. This won't work

**Comment by mcm1957** [comment]
A repo with an adapter already exists - but the adapter is not yet available at the rpository.
https://github.com/mobilutz/ioBroker.freeathome

**Comment by mobilutz** [comment]
> A repo with an adapter already exists - but the adapter is not yet available at the rpository. [mobilutz/ioBroker.freeathome](https://github.com/mobilutz/ioBroker.freeathome)

The maintainer of the linked adapter from above.

There are unfortunately some things which need to be done before I can release the adapter. But as most people who volunteer with open-source - time is always limited 😦 

I do not want to give any timeline when it will be in the adapter repository, but hope that it will be at some point. Whoever is willing to support -> more than welcome.

**Comment by mcm1957** [comment]
If you need support for any problem finalizing the adapter, I'm sure several people would help. Fell free to ask here or at the ioBroker telegram channel https://t.me/ioBroker_development.

**Comment by SISE469** [comment]
> A repo with an adapter already exists - but the adapter is not yet available at the rpository.
> https://github.com/mobilutz/ioBroker.freeathome

Sorry, I'm an absolute beginner.  Can this adapter already be used in iobroker even though it is not yet available in the repository?  How exactly?

**Comment by mcm1957** [comment]
As the dev dis not react on comments at PR the request to add to latest has been cancelled.

So this adapter seems to need some rework / new maintainer
