### ISSUE TITLE
BYD Battery-Box HV

### ISSUE THREAD

**Issue by p-vitt** [ioBroker/AdapterRequests#456]
There isn't much information on the manufacturers website. Also the data sheet don't give you anything about interfaces:

- https://www.manualslib.com/manual/1603124/Byd-Battery-Box-Hv.html?page=5#manual

- https://solar-distribution.baywa-re.de/out/media/4-B-Box_H_6_-_10_2019-04-15_Battery-Box_HV_Datasheet_EN_V1.6_042019.pdf

However, the web frontend provides some informtion. E.g. http://1.2.3.4/asp/RunData.asp has detailed information about each battery module, Home.asp returns some more common things.

I don't know about more sophisticated interfaces (like JSON, ...) yet.

**Comment by p-vitt** [comment]
So, I just [started an adapter](https://github.com/p-vitt/ioBroker.byd-batterybox). As I'm pretty new to ioBroker as well as JS, don't expected much soon. However, any help appreciated.

**Comment by p-vitt** [comment]
Sorry, I'm pretty busy at the moment, and wasn't aware that I need to respond to something. Hopefully I find time this evening to extract the sources. Meanwhile, I did some of the extractions using the parser module. Works pretty fine.

**Comment by MirkoHuf** [comment]
Hi @p-vitt and @bazidibavaria 
I have a BYD Battery as well and maybe I can help too. Have you already started with the adapter?

**Comment by p-vitt** [comment]
> Hi @p-vitt and @bazidibavaria
> I have a BYD Battery as well and maybe I can help too. Have you already started with the adapter?

Hi @MirkoHuf

As I already mentioned, I at least started a [new repository with an adapter stub](https://github.com/p-vitt/ioBroker.byd-batterybox). However, due to several reasons, I'm out of spare time for the next weeks/months, so I didn't do anything more. I got the most important information using the parser module, so the pressure to create a dedicated adapter also lowered a lot. But you can of course use the [repo](https://github.com/p-vitt/ioBroker.byd-batterybox) or start one on your own. I just can't promise if/when I can be of any help.

**Comment by arteck** [comment]
adapter is ready to test
https://github.com/arteck/iobroker.bydbatt

**Comment by MirkoHuf** [comment]
Perfect - works very well for me with 1 Array and 8 Batteries.

Am Sa., 26. Dez. 2020 um 20:50 Uhr schrieb arteck <notifications@github.com

**Comment by ck-coke** [comment]
`
I'm getting these messages: What can I check? Password in BYD is set and IP is correct. Bat Count as well.
--
2021-01-06 19:51:51.595  - info: bydbatt.0 (23325) cleaned everything up...
2021-01-06 19:51:52.306  - info: bydbatt.0 (23325) terminating
2021-01-06 19:51:52.310  - info: bydbatt.0 (23325) Terminated (NO_ERROR): Without reason
2021-01-06 19:51:52.313  - info: bydbatt.0 (23325) terminating
2021-01-06 19:51:52.844  - info: host.smarthome instance system.adapter.bydbatt.0 terminated with code 0 (NO_ERROR)
2021-01-06 19:51:52.845  - info: host.smarthome Restart adapter system.adapter.bydbatt.0 because enabled
2021-01-06 19:52:22.878  - info: host.smarthome instance system.adapter.bydbatt.0 started with pid 23340
2021-01-06 19:52:25.288  - info: bydbatt.0 (23340) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.bydbatt, node: v14.15.1, js-controller: 3.1.6
2021-01-06 19:52:26.108  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-01-06 19:52:26.109  - error: bydbatt.0 (23340) unhandled promise rejection: Request failed with status code 401
2021-01-06 19:52:26.112  - error: bydbatt.0 (23340) Error: Request failed with status code 401
at createError (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-01-06 19:52:26.115  - info: bydbatt.0 (23340) cleaned everything up...
2021-01-06 19:52:26.683  - info: bydbatt.0 (23340) terminating
2021-01-06 19:52:26.687  - info: bydbatt.0 (23340) Terminated (NO_ERROR): Without reason
2021-01-06 19:52:26.693  - info: bydbatt.0 (23340) terminating
2021-01-06 19:52:27.217  - info: host.smarthome instance system.adapter.bydbatt.0 terminated with code 0 (NO_ERROR)
2021-01-06 19:52:27.218  - info: host.smarthome Restart adapter system.adapter.bydbatt.0 because enabled
2021-01-06 19:52:57.248  - info: host.smarthome instance system.adapter.bydbatt.0 started with pid 23357
2021-01-06 19:52:59.891  - info: bydbatt.0 (23357) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.bydbatt, node: v14.15.1, js-controller: 3.1.6
2021-01-06 19:53:00.451  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-01-06 19:53:00.452  - error: bydbatt.0 (23357) unhandled promise rejection: Request failed with status code 401
2021-01-06 19:53:00.455  - error: bydbatt.0 (23357) Error: Request failed with status code 401
at createError (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-01-06 19:53:00.457  - info: bydbatt.0 (23357) cleaned everything up...
2021-01-06 19:53:01.084  - info: bydbatt.0 (23357) terminating
2021-01-06 19:53:01.088  - info: bydbatt.0 (23357) Terminated (NO_ERROR): Without reason
2021-01-06 19:53:01.093  - info: bydbatt.0 (23357) terminating
2021-01-06 19:53:01.622  - info: host.smarthome instance system.adapter.bydbatt.0 terminated with code 0 (NO_ERROR)
2021-01-06 19:53:01.623  - info: host.smarthome Restart adapter system.adapter.bydbatt.0 because enabled

`

**Comment by ldittmar81** [comment]
@Apollon77 Its stable... can be closed.
