### ISSUE TITLE
Yeedi 2 Hybrid Saugroboter Adapter für ioBroker

### ISSUE THREAD

**Issue by biker1602** [ioBroker/AdapterRequests#643]
**What kind of device or service you would like to see an adapter for?**
Add name and company of the device, including links to the device and any additional informations[...]

https://www.amazon.de/yeedi-Saugroboter-Wischfunktion-Visual-SLAM-Navigation-Saugleistung/dp/B08JV8VL1N

**Is an official API including documentation is available?**
If yes please add links and informations[...]
Nein

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

Leider nein

**Is this device already integrated in other Smart Home systems?**
Add Links please

Ja mit Alexa und Play store mit App Yeedi

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

Weiß ich leider nicht

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mrbungle64** [comment]
@biker1602 

Der Yeedi 2 Hybrid könnte rein theoretisch mit dem Ecovacs Deebot Adapter funktionieren.

Kannst Du oder jmd anders mit diesem Modell mal probieren, ob das Gerät erkannt wird?

Bitte nicht erwarten, dass der dann direkt in vollem Umfang funktioniert - es geht erst mal nur darum, ob das Gerät über die Ecovacs Infrastruktur verfügbar ist.

Falls das Gerät erkannt wird:
es müsste dann im Log eine Zeile auftauchen die mit `Device[0]` beginnt. In dieser Zeile ist dann u.a. eine `class` aufgeführt - der Wert müsste dann `p5nx9u` sein.

**Comment by biker1602** [comment]
@mrbungle64 
Ja das habe ich damals auch gedacht und auch schon versucht. Ich habe es eben aber nochmal versucht aber die Registrierungsdaten von der Yeedi 2 Hybrid App bekommt er im iobroker Adapter keine Verbindung. Ich habe dann noch versucht die App von Ecovacs zu installieren mich registriert und habe versucht ihn zu koppeln aber das klappt leider auch nicht

**Comment by mrbungle64** [comment]
@biker1602 
Was wird denn im Log vom ioBroker ausgegeben, während der Adapter versucht zu connecten?

**Comment by biker1602** [comment]
So habe den Adapter nochmal gestartet und es kommen sofort die roten Meldungen im Log
<html><body>


.catch().
--
2021-08-23 08:44:38.926  - error: ecovacs-deebot.0 (8438) unhandled promise rejection: Cannot read property 'nick' of undefined
2021-08-23 08:44:38.928  - error: ecovacs-deebot.0 (8438) TypeError: Cannot read property 'nick' of undefined
at /opt/iobroker/node_modules/iobroker.ecovacs-deebot/main.js:558:36
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-08-23 08:44:38.929  - error: ecovacs-deebot.0 (8438) Cannot read property 'nick' of undefined
2021-08-23 08:44:38.941  - info: ecovacs-deebot.0 (8438) terminating
2021-08-23 08:44:38.943  - warn: ecovacs-deebot.0 (8438) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-23 08:44:39.707  - error: host.raspberrypi instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-23 08:44:39.708  - info: host.raspberrypi Restart adapter system.adapter.ecovacs-deebot.0 because enabled
2021-08-23 08:45:00.097  - info: host.raspberrypi instance system.adapter.daswetter.0 started with pid 8481
2021-08-23 08:45:09.785  - info: host.raspberrypi instance system.adapter.ecovacs-deebot.0 started with pid 8496
2021-08-23 08:45:12.190  - info:  ecovacs-deebot.0 (8496) starting. Version 1.2.1 in  /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.17.0,  js-controller: 3.3.15
2021-08-23 08:45:12.994  - info: ecovacs-deebot.0 (8496) Successfully connected to Ecovacs server
2021-08-23 08:45:12.996  - info: ecovacs-deebot.0 (8496) Number of devices: 0
2021-08-23 08:45:12.996  - info: ecovacs-deebot.0 (8496) Using device Device[0]
2021-08-23 08:45:13.000  - error:  ecovacs-deebot.0 (8496) Unhandled promise rejection. This error  originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2021-08-23 08:45:13.000  - error: ecovacs-deebot.0 (8496) unhandled promise rejection: Cannot read property 'nick' of undefined
2021-08-23 08:45:13.001  - error: ecovacs-deebot.0 (8496) TypeError: Cannot read property 'nick' of undefined
at /opt/iobroker/node_modules/iobroker.ecovacs-deebot/main.js:558:36
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-08-23 08:45:13.002  - error: ecovacs-deebot.0 (8496) Cannot read property 'nick' of undefined
2021-08-23 08:45:13.011  - info: ecovacs-deebot.0 (8496) terminating
2021-08-23 08:45:13.013  - warn: ecovacs-deebot.0 (8496) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-23 08:45:13.740  - error: host.raspberrypi instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-23 08:45:13.741  - info: host.raspberrypi Restart adapter system.adapter.ecovacs-deebot.0 because enabled
2021-08-23 08:45:29.651  - info: host.raspberrypi instance system.adapter.daswetter.0 terminated with code 0 (NO_ERROR)
2021-08-23 08:45:43.805  - info: host.raspberrypi instance system.adapter.ecovacs-deebot.0 started with pid 8521
2021-08-23 08:45:45.901  - info:  ecovacs-deebot.0 (8521) starting. Version 1.2.1 in  /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.17.0,  js-controller: 3.3.15
2021-08-23 08:45:46.598  - info: ecovacs-deebot.0 (8521) Successfully connected to Ecovacs server
2021-08-23 08:45:46.599  - info: ecovacs-deebot.0 (8521) Number of devices: 0
2021-08-23 08:45:46.600  - info: ecovacs-deebot.0 (8521) Using device Device[0]
2021-08-23 08:45:46.603  - error:  ecovacs-deebot.0 (8521) Unhandled promise rejection. This error  originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2021-08-23 08:45:46.603  - error: ecovacs-deebot.0 (8521) unhandled promise rejection: Cannot read property 'nick' of undefined
2021-08-23 08:45:46.605  - error: ecovacs-deebot.0 (8521) TypeError: Cannot read property 'nick' of undefined
at /opt/iobroker/node_modules/iobroker.ecovacs-deebot/main.js:558:36
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-08-23 08:45:46.605  - error: ecovacs-deebot.0 (8521) Cannot read property 'nick' of undefined
2021-08-23 08:45:46.612  - info: ecovacs-deebot.0 (8521) terminating
2021-08-23 08:45:46.614  - warn: ecovacs-deebot.0 (8521) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-23 08:45:47.478  - error: host.raspberrypi instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-23 08:45:47.480  - info: host.raspberrypi Restart adapter system.adapter.ecovacs-deebot.0 because enabled
2021-08-23 08:45:47.480  - warn: host.raspberrypi Do not restart adapter system.adapter.ecovacs-deebot.0 because restart loop detected


</body>
</html>

**Comment by mrbungle64** [comment]
@biker1602 

Wieso hast Du die Zeilen gelöscht, wo der erfolgreiche Login ausgegeben wurde?

```
2021-08-23 08:45:12.994 - info: ecovacs-deebot.0 (8496) Successfully connected to Ecovacs server
```

**Comment by biker1602** [comment]
Ich habe da eigentlich nichts gesehen das er sich connected hat.
<html><body>


2021-08-23 19:09:41.289  - info: host.raspberrypi "system.adapter.ecovacs-deebot.0" enabled
--
2021-08-23 19:09:41.875  - info: host.raspberrypi instance system.adapter.ecovacs-deebot.0 started with pid 5779
2021-08-23 19:09:44.060  - info:  ecovacs-deebot.0 (5779) starting. Version 1.2.1 in  /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.17.0,  js-controller: 3.3.15
2021-08-23 19:09:45.545  - info: ecovacs-deebot.0 (5779) Successfully connected to Ecovacs server
2021-08-23 19:09:45.547  - info: ecovacs-deebot.0 (5779) Number of devices: 0
2021-08-23 19:09:45.548  - info: ecovacs-deebot.0 (5779) Using device Device[0]
2021-08-23 19:09:45.553  - error:  ecovacs-deebot.0 (5779) Unhandled promise rejection. This error  originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2021-08-23 19:09:45.553  - error: ecovacs-deebot.0 (5779) unhandled promise rejection: Cannot read property 'nick' of undefined
2021-08-23 19:09:45.555  - error: ecovacs-deebot.0 (5779) TypeError: Cannot read property 'nick' of undefined
at /opt/iobroker/node_modules/iobroker.ecovacs-deebot/main.js:558:36
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-08-23 19:09:45.556  - error: ecovacs-deebot.0 (5779) Cannot read property 'nick' of undefined
2021-08-23 19:09:45.567  - info: ecovacs-deebot.0 (5779) terminating
2021-08-23 19:09:45.569  - warn: ecovacs-deebot.0 (5779) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-23 19:09:47.340  - error: host.raspberrypi instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-23 19:09:47.343  - info: host.raspberrypi Restart adapter system.adapter.ecovacs-deebot.0 because enabled
2021-08-23 19:10:17.428  - info: host.raspberrypi instance system.adapter.ecovacs-deebot.0 started with pid 5825
2021-08-23 19:10:19.622  - info:  ecovacs-deebot.0 (5825) starting. Version 1.2.1 in  /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.17.0,  js-controller: 3.3.15
2021-08-23 19:10:20.341  - info: ecovacs-deebot.0 (5825) Successfully connected to Ecovacs server
2021-08-23 19:10:20.342  - info: ecovacs-deebot.0 (5825) Number of devices: 0
2021-08-23 19:10:20.343  - info: ecovacs-deebot.0 (5825) Using device Device[0]
2021-08-23 19:10:20.346  - error:  ecovacs-deebot.0 (5825) Unhandled promise rejection. This error  originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2021-08-23 19:10:20.346  - error: ecovacs-deebot.0 (5825) unhandled promise rejection: Cannot read property 'nick' of undefined
2021-08-23 19:10:20.348  - error: ecovacs-deebot.0 (5825) TypeError: Cannot read property 'nick' of undefined
at /opt/iobroker/node_modules/iobroker.ecovacs-deebot/main.js:558:36
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-08-23 19:10:20.348  - error: ecovacs-deebot.0 (5825) Cannot read property 'nick' of undefined
2021-08-23 19:10:20.356  - info: ecovacs-deebot.0 (5825) terminating
2021-08-23 19:10:20.357  - warn: ecovacs-deebot.0 (5825) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-23 19:10:21.106  - error: host.raspberrypi instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-23 19:10:21.107  - info: host.raspberrypi Restart adapter system.adapter.ecovacs-deebot.0 because enabled


</body>
</html>

**Comment by biker1602** [comment]
@mrbungle64 
Sag mal meinst du, wenn ich mich bei der Yeedi App abmelde, und mich über die Ecovacs App anmelde und versuche das Gerät zu verbinden und es nicht funktioniert, dass ich mich ohne weiteres wieder bei der Yeedi App anmelden kann und die aufgezeichnete Karte auch dann noch da ist? Ich habe Angst das die Karte weg ist da ich nicht weiß, wo sie gespeichert ist.
Wie gesagt ich bin mir gar nicht sicher, ob die Ecovacs App funktioniert und welcher Saugroboter da identisch ist. Hast du da eine Ahnung?

**Comment by mrbungle64** [comment]
@biker1602 

> @mrbungle64
> Sag mal meinst du, wenn ich mich bei der Yeedi App abmelde, und mich über die Ecovacs App anmelde und versuche das Gerät zu verbinden und es nicht funktioniert, dass ich mich ohne weiteres wieder bei der Yeedi App anmelden kann und die aufgezeichnete Karte auch dann noch da ist? Ich habe Angst das die Karte weg ist da ich nicht weiß, wo sie gespeichert ist.
> Wie gesagt ich bin mir gar nicht sicher, ob die Ecovacs App funktioniert und welcher Saugroboter da identisch ist. Hast du da eine Ahnung?

Über die Ecovacs App würde ich das nicht versuchen - das wird eher nicht funktionieren.
Da wird auch kein Ecovacs Modell wirklich identisch sein. Das war auch gar nicht mein Gedanke.

Die Yeedi Modelle sind aber zusammen mit den Ecovacs Modellen gelistet, wenn man sich die Modelle [über die Ecovacs API](https://portal-eu.ecouser.net/api/pim/product/getConfigProducts) als JSON ausgeben lässt:

```js
...
        {
            "groupId": "5f0d4383dedb470008507e49",
            "groupName": "yeedi 2 hybrid",
            "robotList":
            [
                {
                    "classid": "p5nx9u",
                    "icon": "https://portal-ww.ecouser.net/api/pim/file/get/5f59e774c0f03a0008ee72e0",
                    "qrCode": "",
                    "robotId": "5f0d45404a3cbe00073d17db",
                    "robotName": "yeedi 2 hybrid",
                    "status": "valid"
                }
            ]
        },
...
```

Aktuell sind dort folgende Modelle aufgeführt:
- yeedi 2 hybrid
- yeedi mop station
- yeedi vac hybrid
- yeedi vac series (vac, vac max, vac station)

Deswegen ist es auch nicht ganz ausgeschlossen, dass man diese Yeedi Modelle über die Ecovacs API steuern kann.
Der Login scheint ja wie gesagt erfolgreich gewesen zu sein. Ich schätze mal, dass es da eine Art Namespace gibt - jeweils getrennt für Ecovacs und Yeedi Modelle.

**Comment by biker1602** [comment]
@mrbungle64 jetzt kommt das Problem bei mir, das ich dir leider nicht mehr folgen kann. Ich weiß gar nicht wie ich das hinkomme und was ich da machen oder ändern kann.

**Comment by mrbungle64** [comment]
@biker1602 

> @mrbungle64 jetzt kommt das Problem bei mir, das ich dir leider nicht mehr folgen kann. Ich weiß gar nicht wie ich das hinbekommen soll und wo und was ich da machen oder ändern kann.

Du kannst da aktuell evtl. nicht viel machen - es sei denn Du weißt wie man den (transportverschlüsselten) Netzwerkverkehr der App sniffen kann.

**Comment by mrbungle64** [comment]
@biker1602 

könntest du mal folgendes probieren:

* den Ecovacs Deebot Adapter installieren
* in der Datei /opt/iobroker/node_modules/ecovacs-deebot/library/ecovacsConstants.js jeweils "ecovacs" durch "yeedi" ersetzen
* in den Adapter Einstellungen die Anmeldedaten vom Yeedi Account eintragen
* Adapter Instanz neu starten

**Comment by biker1602** [comment]
Hallo

Funktioniert Leider nicht.

Daten habe ich geändert leider ohne Erfolg.

 



 

 



 

Am Anfang war der Verbunden mit Host noch grün wurde dann aber auch wieder rot.

Ich habe es mit der Mail und auch mit der Geräte ID versucht.

 

Gruß Ulli

 

 

Von: Sascha ***@***.***> 
Gesendet: Donnerstag, 26. Mai 2022 12:39
An: ioBroker/AdapterRequests ***@***.***>
Cc: biker1602 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Yeedi 2 Hybrid Saugroboter Adapter für ioBroker (#643)

 

@biker1602 <https://github.com/biker1602> 

könntest du mal folgendes probieren:

*	den Ecovacs Deebot Adapter installieren
*	in der Datei /opt/iobroker/node_modules/ecovacs-deebot/library/ecovacsConstants.js jeweils "ecovacs" durch "yeedi" ersetzen
*	in den Adapter Einstellungen die Anmeldedaten vom Yeedi Account eintragen
*	Adapter Instanz neu starten

**Comment by mrbungle64** [comment]
@biker1602 

> Hallo
> Funktioniert Leider nicht.
> Daten habe ich geändert leider ohne Erfolg.
> Am Anfang war der Verbunden mit Host noch grün wurde dann aber auch wieder rot.
> Ich habe es mit der Mail und auch mit der Geräte ID versucht.
> Gruß Ulli

Hallo Ulli,

wir haben inzwischen festgestellt, dass da noch ein paar andere Dinge zu ändern sind.

Ich melde mich wieder, wenn es mir (hoffentlich) gelungen ist in den Ecovacs Deebot Adapter (bzw. die zugehörige Library) Unterstützung für yeedi Modelle einzubauen und es dann was zu testen gibt 😉

**Comment by mrbungle64** [comment]
@biker1602 

Ich werde demnächst eine Version vom Ecovacs Deebot Adapter mit Untersützung für yeedi Modelle rausbringen.
Meine Library kann sich nun soweit bei yeedi anmelden und die wichtigsten Funktionen der "yeedi mop station" funktionieren auch soweit. Werde mich dann nun an die Integration in den Adapter machen.

**Comment by mrbungle64** [comment]
https://forum.iobroker.net/topic/55579/ecovacs-deebot-adapter-yeedi-modelle

**Comment by mrbungle64** [comment]
@biker1602 

Hattest du den Link zu dem Topic im ioBroker Forum gesehen?

https://forum.iobroker.net/topic/55579/ecovacs-deebot-adapter-yeedi-modelle

**Comment by biker1602** [comment]
Oh nein habe den Adapter jetzt installiert und er verbindet sich und holt auch die Daten.

Jetzt muss ich mal schauen wie ich die Datenpunkte zu steuern anwählen kann.

Erstmal vielen Dank

 

Von: Sascha ***@***.***> 
Gesendet: Montag, 13. Juni 2022 12:06
An: ioBroker/AdapterRequests ***@***.***>
Cc: biker1602 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Yeedi 2 Hybrid Saugroboter Adapter für ioBroker (#643)

 

@biker1602 <https://github.com/biker1602> 

Hattest du den Link zu dem Topic im ioBroker Forum gesehen?

https://forum.iobroker.net/topic/55579/ecovacs-deebot-adapter-yeedi-modelle

**Comment by mrbungle64** [comment]
@biker1602 

> ... und er verbindet sich und holt auch die Daten.

Das klingt ja schon mal gut 👍🏻 

> Jetzt muss ich mal schauen wie ich die Datenpunkte zu steuern anwählen kann.

Wir sollten dann im Forum weiter schreiben, oder? Würde mich da über Feedback freuen.

**Comment by mrbungle64** [comment]
@Apollon77 @biker1602 

Ich denke, der Issue sollte geschlossen werden.

Der Ecovacs-Deebot Adapter kann schon seit einiger Zeit mit dem yeedi Login umgehen und unterstützt auch den yeedi 2 hybrid (+ andere yeedi Modelle):
https://forum.iobroker.net/topic/55579/ecovacs-deebot-adapter-yeedi-modelle

Die yeedi Geräte benutzen die (Ecovacs) Deebot API (man kann wohl auch sogar yeedi Geräte dem Ecovacs Account hinzufügen - habe ich selbst aber nicht getestet)

**Comment by mcm1957** [comment]
Seh ich genauso.

Link zum Adapterrepo:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot
