### ISSUE TITLE
Mystrom Adapter CPU utilisation increase blocking ioBroker from working

### ISSUE THREAD

**Issue by Heinz9** [ioBroker/AdapterRequests#936]
Hello all
I’m running a ioBroker in a Docker environment on a small Ubuntu system. My problem is, that ioBroker (within 1-2 days) gets extremely slow (web access response times of over 1' become the norm). 
Only remedial action is then to stop and restart ioBroker manually (as after a certain time no reaction over the web was given at all.
The diagnosis of ioBroker is "unremarkable". 
Only thing strange in my eyes is the process "iobroker.js-con", whose CPU "consumption" increases continuously after a restart and after a certain time on average (not peak) hijacks around 100% CPU performance for this single process. Without a running myStrom instance, the CPU share of “ iobroker.js-con” remains around 30% on average (between approx. 10% and with peaks of approx. 100%). With the myStrom adapter turned on, this value climbs continuously until "nothing works". Attempts to stop the instance or display the status of ioBroker may fail with various error messages but NOT always. It seems to be a timeout question 
Below the errors (if I get them; sorry, I could not pack everything between code-tags...):

`
Connection is closed.
Uncaught Rejection: Error: Objects DB is not allowed to start in the current Multihost environment
    at Redis.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:493:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 Unable to subscribe to evicted Keyspace events from Redis Server: Connection is closed.
 Unable to subscribe to meta namespace "meta." changes: Connection is closed.
Server Cannot start inMem-objects on port 9001: Failed to lock DB file "/opt/iobroker/iobroker-data/objects.jsonl"!
root@iobroker:/opt/iobroker# iobroker stop mystrom
No connection to databases possible ...
/opt/iobroker/node_modules/standard-as-callback/built/index.js:6
`
      throw e;
      ^
`
Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)
`
`
Emitted 'error' event on ScanStream instance at:
    at /opt/iobroker/node_modules/ioredis/built/ScanStream.js:38:22
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:12:23)
    at /opt/iobroker/node_modules/standard-as-callback/built/index.js:33:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.19.1
`

It took me a while to find the suspect in the MyStrom adapter. I can stop it (or kill it); then restart it; afterwards the system runs smoothly again for a while and the CPU "consumption" stays within normal range first.
As long as the system is still responding, I can restart the instance via the GUI. If not, only killing / restarting the io.mystrom.0 process helps.
With this "half-knowledge" I built a simple Blockly, which stops and restarts this instance every night. This works and keeps ioBroker happy. But that's not supposed to be the definitive solution...
In total I have 10 MyStrom smartswitches and 4 MyStrom buttons installed. I have already massively reduced the refresh times (switches every 3' and buttons only every 5' down from the default).
What additional information do you need to be able to help me?
Below is the "DIAG" information:
Details
```
Skript v.2023-10-10

*** BASE SYSTEM ***
Hardware Vendor : MINIX
Kernel          : x86_64
Userland        : amd64
Docker          : v9.1.1
Virtualization  : Docker
Kernel          : x86_64
Userland        : amd64

Systemuptime and Load:
 19:20:18 up 6 days,  3:52,  0 user,  load average: 3.71, 3.33, 2.98
CPU threads: 4


*** Time and Time Zones ***
Wed Apr 17 17:20:18 UTC 2024
Wed Apr 17 19:20:18 CEST 2024
CEST +0200
Etc/UTC

*** User and Groups ***
root
/root
root

*** X-Server-Setup ***
X-Server:       false
Desktop:
Terminal:


*** MEMORY ***
               total        used        free      shared  buff/cache   available
Mem:            3.9G        2.7G        302M         21M        1.1G        1.2G
Swap:           4.3G        2.3G        2.0G
Total:          8.2G        5.0G        2.3G

         3707 M total memory
         2576 M used memory
         1745 M active memory
         1132 M inactive memory
          288 M free memory
           60 M buffer memory
         1005 M swap cache
         4105 M total swap
         2200 M used swap
         1905 M free swap

*** FILESYSTEM ***
Filesystem     Type     Size  Used Avail Use% Mounted on
overlay        overlay   57G   42G   12G  79% /
tmpfs          tmpfs     64M     0   64M   0% /dev
shm            tmpfs     64M     0   64M   0% /dev/shm
/dev/sda4      ext4     454G  146G  286G  34% /opt/iobroker
/dev/mmcblk0p2 ext4      57G   42G   12G  79% /etc/hosts

Messages concerning ext4 filesystem in dmesg:
[Thu Apr 11 15:28:01 2024] EXT4-fs (mmcblk0p2): mounted filesystem e7008656-f765-4831-beda-f9d3790c6b57 ro with ordered data mode. Quota                                   mode: none.
[Thu Apr 11 15:28:02 2024] EXT4-fs (mmcblk0p2): re-mounted e7008656-f765-4831-beda-f9d3790c6b57 r/w. Quota mode: none.
[Thu Apr 11 15:28:09 2024] EXT4-fs (sda4): mounted filesystem 75fb4010-012d-4f1d-8fc0-dcb99d3eaa4a r/w with ordered data mode. Quota mod                                  e: none.

Show mounted filesystems \(real ones only\):
TARGET           SOURCE                                                                                                                                                    FSTYPE OPTIONS
/opt/iobroker    /dev/sda4[/docker/iobroker]                                                                                                                               ext4   rw,nosuid,nodev,relatime
/etc/resolv.conf /dev/mmcblk0p2[/var/lib/docker/containers/0c32080b22a8f642a80b0fec693e7e001d8fd103da38b92e9a261a25b1623762/resolv.conf]                                   ext4   rw,relatime,errors=remount-ro
/etc/hostname    /dev/mmcblk0p2[/var/lib/docker/containers/0c32080b22a8f642a80b0fec693e7e001d8fd103da38b92e9a261a25b1623762/hostname]                                      ext4   rw,relatime,errors=remount-ro
/etc/hosts       /dev/mmcblk0p2[/var/lib/docker/containers/0c32080b22a8f642a80b0fec693e7e001d8fd103da38b92e9a261a25b1623762/hosts]                                         ext4   rw,relatime,errors=remount-ro

Files in neuralgic directories:

/var:
34M     /var/
32M     /var/lib
19M     /var/lib/apt/lists
19M     /var/lib/apt
13M     /var/lib/dpkg



/opt/iobroker/backups:
4.0K    /opt/iobroker/backups/

/opt/iobroker/iobroker-data:
613M    /opt/iobroker/iobroker-data/
452M    /opt/iobroker/iobroker-data/files
100M    /opt/iobroker/iobroker-data/backup-objects
78M     /opt/iobroker/iobroker-data/files/icons-open-icon-library-png
57M     /opt/iobroker/iobroker-data/files/javascript.admin

The five largest files in iobroker-data are:
41M     /opt/iobroker/iobroker-data/files/material/static/js/main.c5478f66.js.map
35M     /opt/iobroker/iobroker-data/files/devices.admin/static/js/main.24f2bb56.js.map
33M     /opt/iobroker/iobroker-data/files/iot.admin/static/js/main.1797d034.js.map
31M     /opt/iobroker/iobroker-data/objects.jsonl
30M     /opt/iobroker/iobroker-data/states.jsonl

USB-Devices by-id:
USB-Sticks -  Avoid direct links to /dev/* in your adapter setups, please always prefer the links 'by-id':

find: '/dev/serial/by-id/': No such file or directory

*** NodeJS-Installation ***

/usr/bin/nodejs         v18.20.2
/usr/bin/node           v18.20.2
/usr/bin/npm            10.5.0
/usr/bin/npx            10.5.0
/usr/bin/corepack       0.25.2


nodejs:
  Installed: 18.20.2-1nodesource1
  Candidate: 18.20.2-1nodesource1
  Version table:
 *** 18.20.2-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
        100 /var/lib/dpkg/status
     18.20.1-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.20.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.19.1-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.19.0+dfsg-6~deb12u1 500
        500 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages
     18.19.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.18.2-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.18.1-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.18.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.17.1-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.17.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.16.1-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.16.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.15.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.14.2-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.14.1-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.14.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.13.0+dfsg1-1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
     18.13.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.12.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.11.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.10.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.9.1-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.9.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.8.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.7.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.6.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.5.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.4.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.3.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.2.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.1.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
     18.0.0-1nodesource1 1001
       1001 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages

Temp directories causing npm8 problem: 0
No problems detected

Errors in npm tree:

*** ioBroker-Installation ***

ioBroker Status
iobroker is running on this host.


Objects type: jsonl
States  type: jsonl

Core adapters versions
js-controller:  5.0.19
admin:          6.13.16
javascript:     7.8.0

Adapters from github:   0

Adapter State
+ system.adapter.admin.0                  : admin                 : iobroker                                 -  enabled, port: 8081, bin                                  d: 0.0.0.0, run as: admin
  system.adapter.alias-manager.0          : alias-manager         : iobroker                                 -  enabled
+ system.adapter.backitup.0               : backitup              : iobroker                                 -  enabled
  system.adapter.backitup.1               : backitup              : iobroker                                 - disabled
+ system.adapter.chromecast.0             : chromecast            : iobroker                                 -  enabled
  system.adapter.daswetter.0              : daswetter             : iobroker                                 - disabled
+ system.adapter.device-watcher.0         : device-watcher        : iobroker                                 -  enabled
  system.adapter.devices.0                : devices               : iobroker                                 -  enabled
  system.adapter.energiefluss.0           : energiefluss          : iobroker                                 - disabled
  system.adapter.foobar2000.0             : foobar2000            : iobroker                                 - disabled, port: 8888
  system.adapter.frontier_silicon.0       : frontier_silicon      : iobroker                                 - disabled
+ system.adapter.harmony.0                : harmony               : iobroker                                 -  enabled
  system.adapter.history.0                : history               : iobroker                                 - disabled
+ system.adapter.hm-rega.0                : hm-rega               : iobroker                                 -  enabled
+ system.adapter.hm-rpc.0                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hm-rpc.1                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hm-rpc.2                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hm-rpc.3                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hue.0                    : hue                   : iobroker                                 -  enabled, port: 443
  system.adapter.icons-mfd-png.0          : icons-mfd-png         : iobroker                                 -  enabled
  system.adapter.icons-mfd-svg.0          : icons-mfd-svg         : iobroker                                 -  enabled
  system.adapter.icons-open-icon-library-png.0: icons-open-icon-library-png: iobroker                                 -  enabled
+ system.adapter.influxdb.0               : influxdb              : iobroker                                 -  enabled, port: 8086
  system.adapter.iot.0                    : iot                   : iobroker                                 - disabled
  system.adapter.jarvis.0                 : jarvis                : iobroker                                 - disabled
+ system.adapter.javascript.0             : javascript            : iobroker                                 -  enabled
  system.adapter.lovelace.0               : lovelace              : iobroker                                 - disabled, port: 8091, bin                                  d: 0.0.0.0, run as: admin
  system.adapter.material.0               : material              : iobroker                                 -  enabled
  system.adapter.musiccast.0              : musiccast             : iobroker                                 - disabled
+ system.adapter.mystrom.0                : mystrom               : iobroker                                 -  enabled
+ system.adapter.parser.0                 : parser                : iobroker                                 -  enabled
+ system.adapter.ping.0                   : ping                  : iobroker                                 -  enabled
+ system.adapter.shelly.0                 : shelly                : iobroker                                 -  enabled, port: 1882, bin                                  d: 0.0.0.0
+ system.adapter.simple-api.0             : simple-api            : iobroker                                 -  enabled, port: 8087, bin                                  d: 0.0.0.0, run as: admin
+ system.adapter.smartgarden.0            : smartgarden           : iobroker                                 -  enabled
  system.adapter.swiss-weather-api.0      : swiss-weather-api     : iobroker                                 - disabled
+ system.adapter.swiss-weather-api.1      : swiss-weather-api     : iobroker                                 -  enabled
+ system.adapter.synology.0               : synology              : iobroker                                 -  enabled, port: 5000
+ system.adapter.synology.1               : synology              : iobroker                                 -  enabled, port: 5000
  system.adapter.vis-bars.0               : vis-bars              : iobroker                                 -  enabled
  system.adapter.vis-colorpicker.0        : vis-colorpicker       : iobroker                                 -  enabled
  system.adapter.vis-hqwidgets.0          : vis-hqwidgets         : iobroker                                 -  enabled
  system.adapter.vis-icontwo.0            : vis-icontwo           : iobroker                                 -  enabled
+ system.adapter.vis-inventwo.0           : vis-inventwo          : iobroker                                 -  enabled
  system.adapter.vis-jqui-mfd.0           : vis-jqui-mfd          : iobroker                                 -  enabled
  system.adapter.vis-material-advanced.0  : vis-material-advanced : iobroker                                 -  enabled
  system.adapter.vis-materialdesign.0     : vis-materialdesign    : iobroker                                 -  enabled
  system.adapter.vis.0                    : vis                   : iobroker                                 -  enabled
+ system.adapter.web.0                    : web                   : iobroker                                 -  enabled, port: 8982, bin                                  d: 0.0.0.0, run as: admin
+ system.adapter.whatsapp-cmb.0           : whatsapp-cmb          : iobroker                                 -  enabled
+ system.adapter.yamaha.0                 : yamaha                : iobroker                                 -  enabled

+ instance is alive

Enabled adapters with bindings
+ system.adapter.admin.0                  : admin                 : iobroker                                 -  enabled, port: 8081, bin                                  d: 0.0.0.0, run as: admin
+ system.adapter.hm-rpc.0                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hm-rpc.1                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hm-rpc.2                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hm-rpc.3                 : hm-rpc                : iobroker                                 -  enabled, port: 0
+ system.adapter.hue.0                    : hue                   : iobroker                                 -  enabled, port: 443
+ system.adapter.influxdb.0               : influxdb              : iobroker                                 -  enabled, port: 8086
+ system.adapter.shelly.0                 : shelly                : iobroker                                 -  enabled, port: 1882, bin                                  d: 0.0.0.0
+ system.adapter.simple-api.0             : simple-api            : iobroker                                 -  enabled, port: 8087, bin                                  d: 0.0.0.0, run as: admin
+ system.adapter.synology.0               : synology              : iobroker                                 -  enabled, port: 5000
+ system.adapter.synology.1               : synology              : iobroker                                 -  enabled, port: 5000
+ system.adapter.web.0                    : web                   : iobroker                                 -  enabled, port: 8982, bin                                  d: 0.0.0.0, run as: admin

ioBroker-Repositories
stable        : http://download.iobroker.net/sources-dist.json
beta          : http://download.iobroker.net/sources-dist-latest.json

Active repo(s): stable

Installed ioBroker-Instances
Used repository: stable
Adapter    "admin"        : 6.13.16  , installed 6.13.16
Adapter    "alias-manager": 1.2.6    , installed 1.2.6
Adapter    "backitup"     : 2.11.0   , installed 2.10.11 [Updatable]
Adapter    "chromecast"   : 3.2.0    , installed 3.2.0
Adapter    "daswetter"    : 3.1.13   , installed 3.1.13
Adapter    "device-watcher": 2.11.0  , installed 2.11.0
Adapter    "devices"      : 1.1.5    , installed 1.1.5
Adapter    "discovery"    : 4.4.0    , installed 4.4.0
Adapter    "energiefluss" : 3.6.0    , installed 3.6.0
Adapter    "energiefluss-erweitert": 0.3.0, installed 0.3.0
Adapter    "foobar2000"   : 2.1.0    , installed 2.1.0
Adapter    "frontier_silicon": 0.2.0 , installed 0.2.0
Adapter    "harmony"      : 1.3.0    , installed 1.3.0
Adapter    "history"      : 3.0.1    , installed 3.0.1
Adapter    "hm-rega"      : 4.0.0    , installed 4.0.0
Adapter    "hm-rpc"       : 1.16.0   , installed 1.16.0
Adapter    "hue"          : 3.10.2   , installed 3.10.2
Adapter    "icons-mfd-png": 1.2.1    , installed 1.2.1
Adapter    "icons-mfd-svg": 1.2.0    , installed 1.2.0
Adapter    "icons-open-icon-library-png": 0.1.2, installed 0.1.2
Adapter    "influxdb"     : 4.0.2    , installed 4.0.2
Adapter    "iot"          : 2.0.11   , installed 2.0.11
Adapter    "jarvis"       : 3.1.8    , installed 3.1.8
Adapter    "javascript"   : 7.8.0    , installed 7.8.0
Controller "js-controller": 5.0.19   , installed 5.0.19
Adapter    "lovelace"     : 4.1.8    , installed 4.1.8
Adapter    "material"     : 1.3.1    , installed 1.3.1
Adapter    "musiccast"    : 1.1.3    , installed 1.1.3
Adapter    "mystrom"      : 0.0.14   , installed 0.0.14
Adapter    "parser"       : 2.1.0    , installed 2.1.0
Adapter    "ping"         : 1.6.2    , installed 1.6.2
Adapter    "shelly"       : 6.8.0    , installed 6.8.0
Adapter    "simple-api"   : 2.7.2    , installed 2.7.2
Adapter    "smartgarden"  : 2.0.0    , installed 2.0.0
Adapter    "socketio"     : 6.6.1    , installed 6.6.1
Adapter    "swiss-weather-api": 2.1.0, installed 2.1.0
Adapter    "synology"     : 3.0.1    , installed 3.0.1
Adapter    "vis"          : 1.5.4    , installed 1.5.4
Adapter    "vis-bars"     : 0.1.4    , installed 0.1.4
Adapter    "vis-colorpicker": 2.0.3  , installed 2.0.3
Adapter    "vis-hqwidgets": 1.5.1    , installed 1.5.1
Adapter    "vis-icontwo"  : 1.5.0    , installed 1.5.0
Adapter    "vis-inventwo" : 3.3.3    , installed 3.3.3
Adapter    "vis-jqui-mfd" : 1.1.1    , installed 1.0.12 [Updatable]
Adapter    "vis-material-advanced": 1.7.4, installed 1.7.4
Adapter    "vis-materialdesign": 0.5.9, installed 0.5.9
Adapter    "web"          : 6.2.5    , installed 6.2.5
Adapter    "whatsapp-cmb" : 0.2.3    , installed 0.2.3
Adapter    "ws"           : 2.5.11   , installed 2.5.11
Adapter    "yamaha"       : 0.5.3    , installed 0.5.3

Objects and States
Please stand by - This may take a while
Objects:        22675
States:         19320

*** OS-Repositories and Updates ***
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 https://deb.nodesource.com/node_18.x nodistro InRelease
Reading package lists...
Pending Updates: 0

*** Listening Ports ***
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:9292            0.0.0.0:*               LISTEN      1000       2592581    1358/io.hm-rpc.3
tcp        0      0 127.0.0.11:36197        0.0.0.0:*               LISTEN      0          2573129    -
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      1000       2575651    174/iobroker.js-con
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      1000       2575611    174/iobroker.js-con
tcp        0      0 0.0.0.0:1882            0.0.0.0:*               LISTEN      1000       7984596    205120/io.shelly.0
tcp        0      0 0.0.0.0:2010            0.0.0.0:*               LISTEN      1000       2593151    1351/io.hm-rpc.2
tcp        0      0 0.0.0.0:2001            0.0.0.0:*               LISTEN      1000       2593004    1330/io.hm-rpc.0
tcp        0      0 0.0.0.0:8701            0.0.0.0:*               LISTEN      1000       2592604    1343/io.hm-rpc.1
tcp6       0      0 :::8087                 :::*                    LISTEN      1000       10394213   298635/io.simple-ap
tcp6       0      0 :::8081                 :::*                    LISTEN      1000       2577625    209/io.admin.0
tcp6       0      0 :::61991                :::*                    LISTEN      1000       2578157    536/io.harmony.0
tcp6       0      0 :::8982                 :::*                    LISTEN      1000       7886081    200326/io.web.0
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1000       2578236    485/io.chromecast.0
udp        0      0 0.0.0.0:61991           0.0.0.0:*                           1000       2578158    536/io.harmony.0
udp        0      0 127.0.0.11:58468        0.0.0.0:*                           0          2573128    -

*** Log File - Last 25 Lines ***

Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.117kW]

2024-04-17 19:16:10.351  - info: javascript.0 (197912) script.js.Energie.PV_Leistungsdaten_aktualisieren: [PV_Leistungsdaten_aktualisieren]: Auslöser: [PV-Anlage-Leistung-aktuell] mit Wert: [0.091]
Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.091kW]

2024-04-17 19:17:09.989  - info: javascript.0 (197912) script.js.Energie.PV_Leistungsdaten_aktualisieren: [PV_Leistungsdaten_aktualisieren]: Auslöser: [PV-Anlage-Leistung-aktuell] mit Wert: [0.07100000000000001]
Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.07100000000000001kW]

2024-04-17 19:18:10.327  - info: javascript.0 (197912) script.js.Energie.PV_Leistungsdaten_aktualisieren: [PV_Leistungsdaten_aktualisieren]: Auslöser: [PV-Anlage-Leistung-aktuell] mit Wert: [0.054]
Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.054kW]

2024-04-17 19:19:10.246  - info: javascript.0 (197912) script.js.Energie.PV_Leistungsdaten_aktualisieren: [PV_Leistungsdaten_aktualisieren]: Auslöser: [PV-Anlage-Leistung-aktuell] mit Wert: [0.046]
Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.046kW]

2024-04-17 19:20:00.034  - info: javascript.0 (197912) script.js.Energie.Status_Einspeisung_PV-Anlage_aktualisieren: Neuer Wert in Variable [Status_PV_Einspeisng] geschrieben. Wert ist: [0] (0 = PV aus / 1 = PV ein aber Leistung < als Verbrauch /  2 = Einspeisen ins EKZ Netz)
2024-04-17 19:20:09.959  - info: javascript.0 (197912) script.js.Energie.PV_Leistungsdaten_aktualisieren: [PV_Leistungsdaten_aktualisieren]: Auslöser: [PV-Anlage-Leistung-aktuell] mit Wert: [0.048]
Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.048kW]

2024-04-17 19:21:10.079  - info: javascript.0 (197912) script.js.Energie.PV_Leistungsdaten_aktualisieren: [PV_Leistungsdaten_aktualisieren]: Auslöser: [PV-Anlage-Leistung-aktuell] mit Wert: [0.058]
Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.058kW]

2024-04-17 19:22:00.018  - info: javascript.0 (197912) script.js.Energie.Status_Einspeisung_PV-Anlage_aktualisieren: Neuer Wert in Variable [Status_PV_Einspeisng] geschrieben. Wert ist: [1] (0 = PV aus / 1 = PV ein aber Leistung < als Verbrauch /  2 = Einspeisen ins EKZ Netz)
2024-04-17 19:22:09.919  - info: javascript.0 (197912) script.js.Energie.PV_Leistungsdaten_aktualisieren: [PV_Leistungsdaten_aktualisieren]: Auslöser: [PV-Anlage-Leistung-aktuell] mit Wert: [0.07100000000000001]
Leistungsdaten für die Strings wurde aktualisiert. Aktuelle abgegebene Leistung ist: [0.07100000000000001kW]


```
Summary
```
======================= SUMMARY =======================
                        v.2023-10-10


model name      : Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz
Kernel          : x86_64
Userland        : amd64
Docker          : v9.1.1

Installation:           Docker
Kernel:                 x86_64
Userland:               amd64
Timezone:               Etc/UTC
User-ID:                0
X-Server:               false


Pending OS-Updates:     14
Pending iob updates:    2

Nodejs-Installation:    /usr/bin/nodejs         v18.19.1
                        /usr/bin/node           v18.19.1
                        /usr/bin/npm            10.2.4
                        /usr/bin/npx            10.2.4
                        /usr/bin/corepack       0.22.0

Recommended versions are nodejs 18.20.2 and npm 10.5.0
Your nodejs installation is correct

MEMORY:
               total        used        free      shared  buff/cache   available
Mem:            3.9G        2.8G        626M         21M        682M        1.1G
Swap:           4.3G        2.2G        2.1G
Total:          8.2G        5.0G        2.7G

Active iob-Instances:   27
Active repo(s): stable

ioBroker Core:          js-controller           5.0.19
                        admin                   6.13.16

ioBroker Status:        iobroker is running on this host.


Objects type: jsonl
States  type: jsonl

Status admin and web instance:
+ system.adapter.admin.0                  : admin                 : iobroker                                 -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.web.0                    : web                   : iobroker                                 -  enabled, port: 8982, bind: 0.0.0.0, run as: admin

Objects:                22675
States:                 19322

Size of iob-Database:

31M     /opt/iobroker/iobroker-data/objects.jsonl
23M     /opt/iobroker/iobroker-data/states.jsonl



=================== END OF SUMMARY ====================
```
Summary:
```
======================= SUMMARY =======================
                        v.2023-10-10


model name      : Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz
Kernel          : x86_64
Userland        : amd64
Docker          : v9.1.1

Installation:           Docker
Kernel:                 x86_64
Userland:               amd64
Timezone:               Etc/UTC
User-ID:                0
X-Server:               false


Pending OS-Updates:     0
Pending iob updates:    2

Nodejs-Installation:    /usr/bin/nodejs         v18.20.2
                        /usr/bin/node           v18.20.2
                        /usr/bin/npm            10.5.0
                        /usr/bin/npx            10.5.0
                        /usr/bin/corepack       0.25.2

Recommended versions are nodejs 18.20.2 and npm 10.5.0
Your nodejs installation is correct

MEMORY:
               total        used        free      shared  buff/cache   available
Mem:            3.9G        2.9G        295M         22M        927M        939M
Swap:           4.3G        2.3G        2.0G
Total:          8.2G        5.2G        2.3G

Active iob-Instances:   27
Active repo(s): stable

ioBroker Core:          js-controller           5.0.19
                        admin                   6.13.16

ioBroker Status:        iobroker is running on this host.


Objects type: jsonl
States  type: jsonl

Status admin and web instance:
+ system.adapter.admin.0                  : admin                 : iobroker                                 -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.web.0                    : web                   : iobroker                                 -  enabled, port: 8982, bind: 0.0.0.0, run as: admin

Objects:                22675
States:                 19320

Size of iob-Database:

31M     /opt/iobroker/iobroker-data/objects.jsonl
31M     /opt/iobroker/iobroker-data/states.jsonl



=================== END OF SUMMARY ====================

```

**Comment by mcm1957** [comment]
Thanks for the detailled problem description.

But this repository is targetted to request new adapters.

I suggest
a) to open atopic at forum (https://forum.iobroker.net) to discuss with other users end to check whther some system setup could cause this problem
b) to open a Issue at the mystrom adapter repository (https://github.com/TA2k/ioBroker.mystrom)

Thanks.
mcm1957
